import './globals.css';
import type { Metadata } from 'next';
import { Croissant_One } from 'next/font/google';

const raleway = Croissant_One({
  subsets: ['latin'],
  weight: '400',
});

export const metadata: Metadata = {
  title: 'Cars Renter 🗿',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={raleway.className}>
        {children}
      </body>
    </html>
  );
}
